nodes:
  # adapi
  - /adapi/node/interface
  - /adapi/node/localization
  - /adapi/node/routing
  - /default_adapi/helpers/autoware_initial_pose_adaptor
  - /default_adapi/helpers/autoware_routing_adaptor

  # caterwil
  - /caterwil_driver_node
  - /caterwil_interface_node
  - /caterwil_joy_controller

  # control
  - /control/simple_pure_pursuit

  # misc
  - /empty_publisher_node
  - /foxglove_bridge
  - /joy_node
  - /robot_state_publisher

  # localization
  - /localization/fast_lio_node
  - /localization/novatel_localizer/novatel_localizer
  - /localization/pose_estimator/ndt_scan_matcher
  - /localization/pose_estimator/voxel_grid_downsample_filter_node
  - /localization/pose_twist_fusion_filter/ekf_localizer
  - /localization/pose_twist_fusion_filter/stop_filter
  - /localization/pose_twist_fusion_filter/twist2accel
  - /localization/twist_estimator/twist_estimator_relay
  - /localization/twist_estimator_node
  - /localization/util/pose_initializer

  # map
  - /map/lanelet2_map_loader
  - /map/lanelet2_map_visualization
  - /map/map_projection_loader
  - /map/pointcloud_map_loader
  - /map/vector_map_tf_generator

  # metrics
  - /metrics/control_performance_analysis

  # planning (бенчмарк: внешний планировщик, perception отключён)
  - /planning/foxglove_visualizer
  - /trajectory_globalizer

  # sensing
  - /sensing/concatenate_and_time_sync_node
  - /sensing/crop_box_filter_inner_node
  - /sensing/crop_box_filter_outer_node
  - /sensing/equirectangular_node
  - /sensing/image_decoder
  - /sensing/imu_filter
  - /sensing/livox_mid360_publisher
  - /sensing/livox_tag_filter_node_50
  - /sensing/livox_tag_filter_node_60
  - /sensing/peakpoints_ud_x1_5_driver
  - /sensing/rewrite_mid360_frames
