# Список топиков для записи в rosbag нодой triggered_bag_recorder.
/**:
  ros__parameters:
    storage_id: mcap  # sqlite3 | mcap
    topics:

      # tf
      - /tf
      - /tf_static

      # sensing
      - /sensing/lidar_10_111_0_50/points_raw
      - /sensing/lidar_10_111_0_60/points_raw
      - /sensing/lidar/concatenated/cropped/pointcloud
      - /image_raw/compressed
      - /sensing/vehicle_velocity_converter/twist_with_covariance
      - /sensing/imu/xsens/data
      - /sensing/imu/xsens/mag
      - /sensing/imu/xsens/temperature
      - /sensing/imu/xsens/velocity

      # localization
      - /localization/kinematic_state
      - /localization/geo_pose_estimator/pose_with_covariance

      # perception
      - /perception/object_recognition/objects
      - /perception/object_recognition/tracking/objects
      - /perception/pointcloud_cluster/objects

      # planning
      - /planning/trajectory
      - /planning/scenario_planning/trajectory

      # control
      - /control/command/control_cmd
