<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>autoware_integration_tools</name>
  <version>1.0.0</version>
  <description>Universal toolkit for implementing temporary solutions for Autoware</description>
  <maintainer email="d.demidov@automacon.ru">Dmitry Demidov</maintainer>
  <maintainer email="a.kondratyev@automacon.ru">Artem Kondratev</maintainer>  
  <maintainer email="r.eydelman@techvill.ru">Roman Eidelman</maintainer>
  <license>Apache-2.0</license>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf_transformations</depend>
  <depend>tf2_ros</depend>
  <depend>sensor_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend> 
  <depend>visualization_msgs</depend> 
  <depend>autoware_planning_msgs</depend> 
  <depend>autoware_control_msgs</depend>
</package>
